### ISSUE TITLE
Any upgrade guide for 2.0?

### ISSUE THREAD

**Issue by PikachuEXE** [kamui/retriable#10]
I know there is the `CHANGELOG.md` file.
But it's unclear to me that what is breaking or not (since it got changes for each beta, not from `1.4.1` to `2.0.0`.

**Comment by kamui** [comment]
I'll write up a condensed CHANGELOG for 2.0.0 and I'll post a wiki entry on how to migrate. 1.x didn't really support exponential backoff, it was mainly a timed interval. 2.x centers around randomized exponential backoff, allows `:on` to accept a `Hash` of Exceptions where the values are Regexp that match against the exception message, and custom `intervals` array.

How were you using 1.x?

**Comment by kamui** [comment]
[CHANGELOG](https://github.com/kamui/retriable/blob/master/CHANGELOG.md) is updated.
[Migrating from 1.x to 2.x](https://github.com/kamui/retriable/wiki/Migrating-to-2.x) wiki entry added.
