### ISSUE TITLE
[Question] Custom Interval

### ISSUE THREAD

**Issue by 404pilot** [kamui/retriable#17]
Hey all,

I am new to ruby and trying to use this gem.

Running following code:

``` ruby
Retriable.retriable intervals: [1, 2, 3, 4] do
  puts "time: #{Time.now}"
  raise 'An error has occured.'
end
```

the result is:

```
time: 2015-09-30 04:04:11 +0000

time: 2015-09-30 04:04:12 +0000

time: 2015-09-30 04:04:14 +0000

time: 2015-09-30 04:04:17 +0000
```

but should it re-try one more time? and the last interval is **4** seconds? I thought the number of execution is original one time plus the size of the interval array?

Thanks.

**Comment by kamui** [comment]
Yep, that's a bug if you specifically pass in an array of intervals. It has to do with` each_with_index` starting the try count at 1 and the equality check expecting it to start at 0. I'll fix this in the next release. Thanks for the report.
