### ISSUE TITLE
"interval is not a valid option" config.rb line 32

### ISSUE THREAD

**Issue by jchatel** [kamui/retriable#38]
Just got my production crash after 3.0.2 just updated

Exception is "interval is not a valid option"

/app/vendor/bundle/ruby/2.2.0/gems/retriable-3.0.2/lib/retriable/config.rb:32

This gem was pulled by google-api-client (that I locked at 0.7.1)

(still looking into what happened... but release of the gem just happened between me looking on staging and deploying prod. Testing staging after the gem update experience same error)

**Comment by jchatel** [comment]
google-api-client didn't lock a version. A slighly newer version had that fixed

**Comment by nitanshu** [comment]
will you please tell on which version of google-api-client with retriable will work
