### ISSUE TITLE
Testing setup

### ISSUE THREAD

**Issue by jgrau** [kamui/retriable#41]
This is probably more of a question than an issue but what's the recommended way to set retriable up in the test environment. Without any specific setup I run into

* The delay makes the tests really slow
* The retry make mocks complain that the retried method is called more than once (which it is, obviously)

Current I made a `config/initializers/retriable.rb` with

```
if Rails.env.test?
  Retriable.configure do |c|
    c.tries = 1
  end
end
```

but I was wondering if there is a better way? Or if there is some documentation on how to do testing that I just didn't find...

Thanks for a great gem!

**Comment by kamui** [comment]
What kind of tests are you writing? Are you testing that code is retried or that some exception is caught? Because, otherwise it shouldn't slow things down if no exception is occurring right?

Otherwise, your approach is probably fine. You could also just override the retriable config in your spec_helper instead or you could check the environment inside the configure block:

```ruby
Retriable.configure do |c|
  if Rails.env.test?
    c.tries = 1
  end
end
```

**Comment by apurvis** [comment]
> You could also just override the retriable config in your spec_helper 

this is the preferred approach where i'm from

**Comment by jeremywadsack** [comment]
> You could also just override the retriable config in your spec_helper

Hmm... the "global" value doesn't seem to override the contexts. 

So, for example, I have this in my `config/initializers/retriable.rb`:

```
Retriable.configure do |c|
  c.contexts[:google_api] = {
      tries:         Settings.google_api.retry_limit,
      base_interval: Settings.google_api.retry_sleep,
      on:            [
          Faraday::SSLError,
          Faraday::ConnectionFailed,
          Faraday::TimeoutError,
          Net::ReadTimeout,
          Signet::AuthorizationError,
          Errno::ECONNRESET,
          OpenSSL::SSL::SSLError
      ]
  }
end
```

And when I set this in `spec/spec_helper.rb` it doesn't change the exponential backoff for the tests in that context:

```
Retriable.configure do |c|
  c.multiplier    = 1.0
  c.rand_factor   = 0.0
  c.base_interval = 0
end
```

I have to explicitly override each of the contexts' values:

```
Retriable.configure do |c|
  c.multiplier    = 1.0
  c.rand_factor   = 0.0
  c.base_interval = 0

  c.contexts[:google_api][:tries]         = 2
  c.contexts[:google_api][:base_interval] = 0
end
```

That makes sense in general — I would expect explicit context's values to override the general one, but that makes it complicated to set the tries and base for all contexts. In the end I came up with this:

```
Retriable.configure do |c|
  c.multiplier    = 1.0
  c.rand_factor   = 0.0
  c.base_interval = 0

  c.contexts.keys.each do |context|
    c.contexts[context][:tries]         = 2
    c.contexts[context][:base_interval] = 0
  end
end
```

Might there be a better way to address this?

**Comment by apurvis** [comment]
> Hmm... the "global" value doesn't seem to override the contexts.

right; this is on purpose.  everything you say here makes sense to me about how to deal with this issue (especially when you are using the new contexts feature).  i don't think i could come up with a better answer, and a few lines of code in `spec_helper.rb` sounds pretty reasonable to me.  `spec_helper.rb` is not generally where the most elegant code lives in a project lol.

i guess it might be slightly smoother if `:global` was also a real context that set the defaults - in which case you would only need the 
```ruby
Retriable.configure do |c|
  c.contexts.keys.each do |context|
    c.contexts[context][:tries]         = 2
    c.contexts[context][:base_interval] = 0
  end
end
```
part...  but that also seems a bit like overkill to avoid a few lines in `spec_helper.rb`

**Comment by apurvis** [comment]
given that this question seems to have come up a few times, i would support a README pull request to explain how to handle it.
