### ISSUE TITLE
Error message on max_elapsed_time

### ISSUE THREAD

**Issue by lsimoneau** [kamui/retriable#42]
If you set a high retry limit (e.g. 100), Retriable will exceed the max elapsed time, but the error message says it reached 100 tries:

```
27 tries in 872.859824735 seconds and 75.33571386221345 seconds until the next try.
Failed after 100 retries with RestClient::ServiceUnavailable: 503 Service Unavailable!
```

It would be nice if it could say that it reached the max elapsed time instead.

**Comment by kamui** [comment]
Are you sure that's this library? I don't think retriable outputs any stats on how many retries were attempted.

**Comment by lsimoneau** [comment]
You're right, sorry I realised that straight away but forgot to close the issue.
