### ISSUE TITLE
rubinius travis failures seem to be due to srand(0) not seeding random the same way

### ISSUE THREAD

**Issue by apurvis** [kamui/retriable#63]
i fixed one issue with the rbx build not even starting by upgrading it to 3.99 (see https://github.com/bundler/bundler/issues/6163 for details) but now it just looks like every spec that compares a many decimal-ed float is failing.  not sure what the answer is or if it's even worth trying to deal with.

check out the build log:
https://travis-ci.org/kamui/retriable/jobs/347208017

**Comment by kamui** [comment]
Moved to Github actions.
