### ISSUE TITLE
Replace houndci

### ISSUE THREAD

**Issue by fatkodima** [kamui/retriable#86]
Wdyt about replacing noisy houndci by plain running of rubocop alongside of testing on travis?
Currently running rubocop locally is not working, but on hound is everything is ok, so how it checks for errors?!

**Comment by kamui** [comment]
Hm, hound should be using the local rubocop config. So local rubocop should be the same as hound. Are you finding it's not?

**Comment by fatkodima** [comment]
@kamui I opened this issue while doing #87. Honestly, I do not remember if I saw some differences.

What I am proposing, is to replace hound with simple rubocop run as a step of CI. Right now, hound makes a lot of unnecessary noise in comments. I think it is better just to have a failing CI build and manually find rubocop violations in build logs.

Feel free to close if you think it is not a problem.

**Comment by kamui** [comment]
I know this is old now, but I'm going to close this and continue to monitor hound. It can be noisy, but I'd like to try to configure it to be useful if possible because I do like being able to have linted comments in the PR vs having to read CI output for linting issues.
