### ISSUE TITLE
cannot load such file -- retriable

### ISSUE THREAD

**Issue by ManuelFrigerio** [kamui/retriable#89]
Hi, I'm trying to use your gem but when I test it I get this error"
`cannot load such file -- retriable`

This is my code:
```
module Integration
  require 'retriable'
  
  class Mailchimp

    def self.method1
      Retriable.retriable do
         raise StandardError
       end
    end

  end
end
```

If I comment out `require 'retriable'` I get the error `uninitialized constant Integration::Mailchimp::Retriable`

Thanks

**Comment by kamui** [comment]
Looks like a namespace issue? I'd require retriable outside of the Integration class and more core, the `Retriable` module should be in the root context/self, so you could try `::Retriable.retriable`, add the `::` in front.
