### ISSUE TITLE
gem 'retriable', '~> 2.0'

### ISSUE THREAD

**Issue by wedy** [kamui/retriable#9]
i added this ``gem 'retriable', '~> 2.0'` into my gemfile as per README, when i run my bundle install it says 'Could not find gem 'retriable (~> 2.0) ruby' in the gems available on this machine'

i just realised there is no 2.0 stable version, it's only beta, wondering when the stable version will be available

**Comment by kamui** [comment]
It should be stable enough to release, but I was hoping to get some time to reorganize some things. I'll try to find the time to do that this weekend, and if not, I might just release it as 2.0.0 anyhow.

**Comment by zenspider** [comment]
release now. tweak later.

**Comment by kamui** [comment]
`2.0.0` released.
