### ISSUE TITLE
Should the `on` argument to `with_context` be additive?

### ISSUE THREAD

**Issue by rspeicher** [kamui/retriable#92]
Assume the following context definition:

```ruby
  c.contexts[:mysql] = {
    tries: 10,
    multiplier: 2.5,
    on: Mysql::DeadlockException
  }
```

When using the context and providing an `on` parameter, I first assumed it would be _added_ to the list of exceptions handled by the context. Instead, it overwrites:

```ruby
Retriable.with_context(:mysql, on: SomeOtherException) do
  # This will only retry on `SomeOtherException`!
end
```

At the very least, it might warrant a callout in the README.

This is the only parameter I'd expect to behave in an additive way. All of the others make sense as overrides to me.

**Comment by sunny** [comment]
From my point of view if makes more sense to have it overwrite the context definition. Making it additive would make it harder to replace the exception and possibily break some code that relies on it being replaced.

A workaround here could be sharing that list in a constant for example:

```rb
MYSQL_RETRIES = [Mysql::DeadlockException]

Retriable.configure do |c|
  c.contexts[:mysql] = {
    tries: 10,
    multiplier: 2.5,
    on: MYSQL_RETRIES
  }
end
```

And reuse it:

```rb
Retriable.with_context(:mysql, on: [MYSQL_RETRIES*, SomeOtherException]) do
  # …
end
```
