### ISSUE TITLE
Timeout::timeout is inherently unsafe

### ISSUE THREAD

**Issue by mohamedhafez** [kamui/retriable#96]
Just a heads up, Timeout::timeout is inherently unsafe (see https://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/ and http://blog.headius.com/2008/02/ruby-threadraise-threadkill-timeoutrb.html).

Thankfully using it isn't on by default so that's good for those of us that don't wish to use it, but perhaps a note to users that they are better off implementing their own timeout methods (e.g. with socket timeout options) might save some people some headache down the line. 

Anyway just throwing it out there, thanks for the awesome library!

**Comment by kamui** [comment]
Looks like we already had a warning in the documentation of this option, but I rewrote it to emphasize the danger and recommendation. I may deprecate this in a future version, since this probably shouldn't be used at all.
